# Generated by Django 4.2.16 on 2024-12-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0002_remove_sku_other_dimensions_remove_sku_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_num', models.IntegerField(default=0, verbose_name='库存数量')),
                ('warehouse', models.CharField(max_length=100, verbose_name='仓库')),
                ('avg_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='平均成本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='gallery.sku', verbose_name='SKU')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'ordering': ['-created_at'],
            },
        ),
    ]
