# Generated by Django 4.2.16 on 2024-12-17 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('category_name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('category_name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.category_image_path, verbose_name='分类图片')),
                ('rank_id', models.IntegerField(default=0, verbose_name='排序ID')),
                ('original_data', models.TextField(blank=True, null=True, verbose_name='原始数据')),
                ('level', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], default=1, verbose_name='分类层级')),
                ('is_last_level', models.BooleanField(default=False, verbose_name='是否最后一级')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'gallery_category',
                'ordering': ['rank_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='SPU ID')),
                ('spu_code', models.CharField(max_length=50, unique=True, verbose_name='SPU编码')),
                ('spu_name', models.CharField(max_length=200, verbose_name='SPU名称')),
                ('spu_remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('sales_channel', models.IntegerField(choices=[(1, '线上'), (2, '线下'), (3, '全渠道')], default=3, verbose_name='销售渠道')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spus', to='gallery.category', verbose_name='所属类目')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU列表',
                'db_table': 'gallery_spu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='SKU ID')),
                ('sku_code', models.CharField(max_length=50, unique=True, verbose_name='SKU编码')),
                ('sku_name', models.CharField(max_length=200, verbose_name='SKU名称')),
                ('provider_name', models.CharField(blank=True, default='无', max_length=100, verbose_name='供应商')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量')),
                ('plating_process', models.CharField(blank=True, choices=[('none', '无电镀'), ('gold', '镀金'), ('silver', '镀银'), ('nickel', '镀镍'), ('chrome', '镀铬'), ('copper', '镀铜'), ('other', '其他')], default='none', max_length=20, verbose_name='电镀工艺')),
                ('length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='长度')),
                ('width', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='宽度')),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='高度')),
                ('other_dimensions', models.CharField(blank=True, max_length=200, null=True, verbose_name='其他尺寸')),
                ('material', models.CharField(blank=True, default='无', max_length=100, verbose_name='材质')),
                ('img_url', models.ImageField(blank=True, null=True, upload_to='skus', verbose_name='产品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('color', models.CharField(blank=True, default='无', max_length=50, verbose_name='颜色')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='gallery.spu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU列表',
                'db_table': 'gallery_sku',
                'ordering': ['-created_at'],
                'permissions': [('sync_sku', 'Can synchronize SKU data')],
            },
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['spu_code'], name='gallery_spu_spu_cod_a8d7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['category'], name='gallery_spu_categor_15b940_idx'),
        ),
        migrations.AddIndex(
            model_name='spu',
            index=models.Index(fields=['sales_channel'], name='gallery_spu_sales_c_8a819a_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['sku_code'], name='gallery_sku_sku_cod_78e1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['spu'], name='gallery_sku_spu_id_d5bb39_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['created_at'], name='gallery_sku_created_d8b747_idx'),
        ),
    ]
